---
recipes:
  - clc:
    - eucalyptus::cloud-controller
    - eucalyptus::register-components
  - user-facing:
    - eucalyptus::user-facing
  - walrus:
    - eucalyptus::walrus
  - cluster-controller:
    - eucalyptus::cluster-controller
  - storage-controller:
    - eucalyptus::storage-controller
  - vmware-broker:
    - eucalyptus::vmware-broker
  - node-controller:
    - eucalyptus::node-controller
  - midolman:
    - midokura::midolman
  - midonet-gw:
    - midokura
  - nuke:
    - eucalyptus::nuke
