---
deployer:
  chef:
    roles:
      - zookeeper:
        - eucalyptus::midokura-repo
        - zookeeper::default
      - cassandra:
        - eucalyptus::midokura-repo
        - cassandra::default
      - clc:
        - eucalyptus::cloud-controller
        - eucalyptus::register-components
      - midonet-cluster:
        - eucalyptus::midokura-repo
        - eucalyptus::midonet-cluster
        - eucalyptus::midolman
      - midolman:
        - eucalyptus::midokura-repo
        - eucalyptus::midolman
      - walrus:
        - eucalyptus::walrus
      - cluster-controller:
        - eucalyptus::cluster-controller
      - storage-controller:
        - eucalyptus::storage-controller
      - node-controller:
        - eucalyptus::node-controller
      - user-facing:
        - eucalyptus::user-facing
      - console:
        - eucalyptus::user-console
      - configure-eucalyptus:
        - eucalyptus::configure
      - configure-vpc:
        - eucalyptus::configure-vpc
      - setup-admin-creds:
        - eucalyptus::setupcreds
