---
deployer:
  chef:
    roles:
      - clc:
        - eucalyptus::cloud-controller
        - eucalyptus::register-components
      - user-facing:
        - eucalyptus::user-facing
        - eucalyptus::user-console
      - walrus:
        - eucalyptus::walrus
      - cluster-controller:
        - eucalyptus::cluster-controller
      - storage-controller:
        - eucalyptus::storage-controller
      - node-controller:
        - eucalyptus::node-controller
      - midolman:
        - midokura::midolman
      - midonet-gw:
        - midokura
